In [2]:
import pandas as pd


In [41]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_a.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_a=pd.concat(data_frame,ignore_index=True)

In [42]:

bigbasket_a.columns


Index(['Unnamed: 0', 'name', 'Category', 'mrp', 'selling_price',
       'offer_percentage', 'delivery_time', 'quantity', 'scrape_date',
       'scrape_time', 'location', 'Delivery_Charges(Handelling+Delivery)',
       'Period', 'Surge', 'Climate', 'Surge_charges', 'Late_Night_Charges',
       'Delivery_Charges(Handelling+Delivery+Late_Night_Charge)'],
      dtype='object')

In [43]:
bigbasket_a

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,11 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,12:32:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,11 MINS,500 g,2026-03-06,12:32:39,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
317,37,fresho! Lemon,Vegetable,33.0,10.0,70% OFF,11 MINS,150 g,2026-03-06,12:32:51,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,11 MINS,100 g,2026-03-06,12:33:02,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0


In [44]:
bigbasket_a[["mrp","Period","Delivery_Charges(Handelling+Delivery)"]].head(10)

,mrp,Period,Delivery_Charges(Handelling+Delivery)
0,Out of Stock,Night,0.0
1,150,Night,26.0
2,32,Night,26.0
3,42,Night,26.0
4,42,Night,26.0
5,Out of Stock,Night,0.0
6,44,Night,26.0
7,63,Night,26.0
8,80,Night,26.0
9,Out of Stock,Night,0.0


In [45]:
bigbasket_a[bigbasket_a["mrp"]!="Out of stock"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,11 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,12:32:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,11 MINS,500 g,2026-03-06,12:32:39,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
317,37,fresho! Lemon,Vegetable,33.0,10.0,70% OFF,11 MINS,150 g,2026-03-06,12:32:51,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,11 MINS,100 g,2026-03-06,12:33:02,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,21.0


In [32]:
bigbasket_a[bigbasket_a["Period"]=="Night"].head(20)

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
5,5,Amul Taaza Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:35:28,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN
6,6,Sids Farm Cow Milk,Milk,44,44,NaN,20 MINS,500 ml,03-03-2026,23:35:39,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
7,7,Sids Farm Buffalo A2 Milk,Milk,63,60,5% OFF,19 MINS,500 ml,03-03-2026,23:35:50,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
8,8,Amul Gold Homogenised Standardised,Milk,80,80,NaN,20 MINS,1 L,03-03-2026,23:36:01,KPHB colony,26.0,Night,NaN,Clear,No,11.0,NaN
9,9,Amul Buffalo Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:36:11,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN


In [61]:
# bigbasket_a["Delivery_Charges(Handelling+Delivery)"]=bigbasket_a["Delivery_Charges(Handelling+Delivery)"]+bigbasket_a["Late_Night_Charges"]

In [114]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [115]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=37.0

In [116]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [117]:
bigbasket_a.loc[((bigbasket_a["mrp"]!="Out of Stock") & (bigbasket_a["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=26.0

In [58]:
bigbasket_a[bigbasket_a["Period"]=="Afternoon"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
280,0,Heritage Fresh Paneer,Paneer,115.0,101.0,12% OFF,11 MINS,200 g - Pouch,2026-03-06,12:26:20,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
281,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-06,12:26:29,Kondapur,NaN,Afternoon,NaN,Sunny,No,NaN,0.0
282,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,11 MINS,500 ml - Pouch,2026-03-06,12:26:39,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
283,3,Heritage Full Cream Milk,Milk,32.0,31.0,3% OFF,11 MINS,500 ml - Pouch,2026-03-06,12:26:49,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
284,4,Arokya Full Cream Milk,Milk,42.0,40.0,5% OFF,11 MINS,500 ml,2026-03-06,12:27:00,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
285,5,Amul Taaza Toned Milk,Milk,16,16,3% OFF,11 MINS,200 ml - Carton,2026-03-06,12:27:10,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
286,6,Sids Farm Cow Milk,Milk,44,44,NaN,11 MINS,500 ml,2026-03-06,12:27:21,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
287,7,Sids Farm Buffalo A2 Milk,Milk,266,266,NaN,11 MINS,200 g,2026-03-06,12:27:31,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
288,8,Amul Gold Homogenised Standardised,Milk,80,80,NaN,11 MINS,1 L,2026-03-06,12:27:41,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0
289,9,Amul Buffalo Milk,Milk,40,40,NaN,11 MINS,500 ml - Pouch,2026-03-06,12:27:51,Kondapur,21.0,Afternoon,NaN,Sunny,No,NaN,21.0


In [73]:
bigbasket_a["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [69]:
bigbasket_a["Delivery_Charges(Handelling+Delivery)"]

0       0.0
1      26.0
2      26.0
3      26.0
4      26.0
       ... 
315    21.0
316    21.0
317    21.0
318    21.0
319    21.0
Name: Delivery_Charges(Handelling+Delivery), Length: 320, dtype: float64

In [81]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_su.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_su=(pd.concat(data_frame,ignore_index=True))

In [153]:
bigbasket_su[bigbasket_su["Period"]=="Night"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([32., nan])

In [143]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [149]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [145]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [146]:
bigbasket_s.loc[((bigbasket_s["mrp"]!="Out of Stock") & (bigbasket_s["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=35.0

In [155]:
bigbasket_s["Delivery_Charges(Handelling+Delivery)"].fillna(0,inplace=True)

C:\Users\veera\AppData\Local\Temp\ipykernel_42572\2310741765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bigbasket_s["Delivery_Charges(Handelling+Delivery)"].fillna(0,inplace=True)


In [157]:
bigbasket_s["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [50]:
bigbasket_su=bigbasket_su.drop(columns="Unnamed: 0")

In [137]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,9):
    file=f"{path}bigbasket_{i}_s.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
bigbasket_s=(pd.concat(data_frame,ignore_index=True))

In [138]:
bigbasket_s

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charges)
0,0,Heritage Fresh Paneer,Paneer,115,101,12% OFF,11 MINS,200 g - Pouch,03-03-2026,23:20:38,Beeramguda,21.0,Night,NaN,Clear,No,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:20:48,Beeramguda,0.0,Night,NaN,Clear,No,NaN
2,2,Heritage Daily Health Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:20:58,Beeramguda,0.0,Night,NaN,Clear,No,NaN
3,3,Heritage Full Cream Milk,Milk,32,31,3% OFF,11 MINS,500 ml - Pouch,03-03-2026,23:21:08,Beeramguda,21.0,Night,NaN,Clear,No,NaN
4,4,Arokya Full Cream Milk,Milk,36,36,NaN,11 MINS,500 ml - Pouch,03-03-2026,23:21:19,Beeramguda,21.0,Night,NaN,Clear,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129,79,39% OFF,8 MINS,1 kg - (Approx. 6 - 8 pcs),06-03-2026,09:09:26,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
316,36,fresho! Mini Orange Imported,Fruit,144,115.2,20% OFF,8 MINS,500 g,06-03-2026,09:09:36,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
317,37,fresho! Lemon,Vegetable,54,38.5,29% OFF,8 MINS,250 g,06-03-2026,09:09:47,Beeramguda,NaN,Morning,NaN,Clear,No,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17,11,35% OFF,8 MINS,100 g,06-03-2026,09:09:57,Beeramguda,NaN,Morning,NaN,Clear,No,21.0


In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Morning")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
blinkit_s[(blinkit_s["mrp"]!="Out of Stock")& (blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna())]=27

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Afternoon")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Evening")),"Delivery_Charges(Handelling+Delivery)"]=21.0

In [ ]:
bigbasket_su.loc[((bigbasket_su["mrp"]!="Out of Stock") & (bigbasket_su["Period"]=="Night")),"Delivery_Charges(Handelling+Delivery)"]=32.0

In [142]:
bigbasket_s[bigbasket_s["Period"]=="Evening"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([nan])

In [158]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,10):
    file=f"{path}blinkit_{i}_a.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_a=(pd.concat(data_frame,ignore_index=True))

In [159]:
blinkit_a

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,13 MINS,200 g,2026-03-03,12:56:15,KPHB colony,36,Afternoon,NaN,sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,13 MINS,240 g,2026-03-03,12:56:29,KPHB colony,36,Afternoon,NaN,sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,13 MINS,500 ml,2026-03-03,12:56:44,KPHB colony,36,Afternoon,NaN,sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:56:59,KPHB colony,36,Afternoon,NaN,sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:57:15,KPHB colony,36,Afternoon,NaN,sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,35,Nagpur - Orange,Fruit,76.0,60,21% OFF,13 MINS,500 g,2026-03-04,23:29:19,KPHB colony,36,Night,NaN,clear,No
356,36,Mini Orange (Imported),Fruit,65.0,57,12% OFF,13 MINS,200 g,2026-03-04,23:29:32,KPHB colony,36,Night,NaN,clear,No
357,37,Lemon (Nimakaya),Vegetable,45.0,36,20% OFF,13 MINS,200 g,2026-03-04,23:29:46,KPHB colony,36,Night,NaN,clear,No
358,38,Green Chilli (Mirapakaya),Vegetable,12.0,11,8% OFF,14 MINS,100 g,2026-03-04,23:29:59,KPHB colony,36,Night,NaN,clear,No


In [162]:
blinkit_a[blinkit_a["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([36, 35])

In [170]:
blinkit_a[blinkit_a["Delivery_Charges(Handelling+Delivery)"]==36]["Period"].unique()

array(['Afternoon', 'Evening', 'Night', 'Morning'], dtype=object)

In [171]:
blinkit_a["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [172]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,11):
    file=f"{path}blinkit_{i}_su.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_su=(pd.concat(data_frame,ignore_index=True))

In [173]:
blinkit_su

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,8 MINS,200 g,2026-03-03,11:53:05,Madhapur,36,Afternoon,NaN,Sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,8 MINS,240 g,2026-03-03,11:53:19,Madhapur,36,Afternoon,NaN,Sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,8 MINS,500 ml,2026-03-03,11:53:33,Madhapur,36,Afternoon,NaN,Sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,8 MINS,500 ml,2026-03-03,11:53:50,Madhapur,36,Afternoon,NaN,Sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,8 MINS,500 ml,2026-03-03,11:54:03,Madhapur,36,Afternoon,NaN,Sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,35,Nagpur - Orange,Fruit,71.0,60,NaN,8 MINS,500 g,2026-03-05,21:15:16,Madhapur,35,Night,NaN,Clear,No
396,36,Mini Orange (Imported),Fruit,77.0,67,12% OFF,8 MINS,200 g,2026-03-05,21:15:28,Madhapur,35,Night,NaN,Clear,No
397,37,Lemon (Nimakaya),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,2026-03-05,21:15:40,Madhapur,0,Night,NaN,Clear,No
398,38,Green Chilli (Mirapakaya),Vegetable,22.0,18,18% OFF,8 MINS,100 g,2026-03-05,21:15:53,Madhapur,35,Night,NaN,Clear,No


In [174]:
blinkit_su["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(0)

In [200]:
path=r"C:\\Users\\veera\\OneDrive\\Desktop\\data_eda\\"
data_frame=[]
for i in range(1,11):
    file=f"{path}blinkit_{i}_s.csv"
    x=pd.read_csv(file)
    data_frame.append(x)
blinkit_s=(pd.concat(data_frame,ignore_index=True))

In [201]:
blinkit_s[blinkit_s["Period"]=="Night"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
80,0,Heritage Fresh Paneer,Paneer,115,101,12% OFF,7 MINS,200 g,03-03-2026,22:28:29,Beeramguda,27.0,Night,NaN,Clear,No
81,1,Heritage Nourish+ High Protein Paneer,Paneer,150,125,16% OFF,7 MINS,240 g,03-03-2026,22:28:42,Beeramguda,27.0,Night,NaN,Clear,No
82,2,Heritage Daily Health Toned Milk,Milk,33,31,6% OFF,7 MINS,450 ml,03-03-2026,22:28:54,Beeramguda,27.0,Night,NaN,Clear,No
83,3,Heritage Full Cream Milk,Milk,42,42,NaN,7 MINS,500 ml,03-03-2026,22:29:06,Beeramguda,27.0,Night,NaN,Clear,No
84,4,Arokya Full Cream Milk,Milk,42,42,NaN,7 MINS,500 ml,03-03-2026,22:29:18,Beeramguda,27.0,Night,NaN,Clear,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,35,Nagpur - Orange,Fruit,70.0,60,14% OFF,14 MINS,500 g,2026-03-05,22:03:27,Beeramguda,27.0,Night,NaN,Clear,No
356,36,Mini Orange (Imported),Fruit,112.0,98,12% OFF,14 MINS,200 g,2026-03-05,22:03:44,Beeramguda,27.0,Night,NaN,Clear,No
357,37,Lemon (Nimakaya),Vegetable,43.0,36,16% OFF,14 MINS,200 g,2026-03-05,22:03:59,Beeramguda,27.0,Night,NaN,Clear,No
358,38,Green Chilli (Mirapakaya),Vegetable,13.0,11,15% OFF,14 MINS,100 g,2026-03-05,22:04:17,Beeramguda,27.0,Night,NaN,Clear,No


In [180]:
blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna().sum()

np.int64(40)

In [202]:
blinkit_s[blinkit_s["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([27., 29., 25., 21., nan])

In [203]:
blinkit_s[blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
240,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,12 MINS,200 g,2026-03-04,23:12:10,Beeramguda,NaN,NaN,NaN,NaN,NaN
241,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,12 MINS,240 g,2026-03-04,23:12:23,Beeramguda,NaN,NaN,NaN,NaN,NaN
242,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,10 MINS,500 ml,2026-03-04,23:12:35,Beeramguda,NaN,NaN,NaN,NaN,NaN
243,3,Heritage Full Cream Milk,Milk,42,42,NaN,10 MINS,500 ml,2026-03-04,23:12:47,Beeramguda,NaN,NaN,NaN,NaN,NaN
244,4,Arokya Full Cream Milk,Milk,42,42,NaN,11 MINS,500 ml,2026-03-04,23:13:00,Beeramguda,NaN,NaN,NaN,NaN,NaN
245,5,Sids Farm Buffalo A2 Milk,Milk,63,63,NaN,11 MINS,500 ml,2026-03-04,23:13:12,Beeramguda,NaN,NaN,NaN,NaN,NaN
246,6,Amul Taaza Toned Milk,Milk,16,16,NaN,11 MINS,200 ml,2026-03-04,23:13:24,Beeramguda,NaN,NaN,NaN,NaN,NaN
247,7,Sids Farm Cow Milk,Milk,44,44,NaN,11 MINS,500 ml,2026-03-04,23:13:37,Beeramguda,NaN,NaN,NaN,NaN,NaN
248,8,Amul Gold Homogenised Standardised,Other,80,80,NaN,11 MINS,1 ltr,2026-03-04,23:13:49,Beeramguda,NaN,NaN,NaN,NaN,NaN
249,9,Amul Buffalo Milk,Milk,59.0,51,13% OFF,11 MINS,450 ml,2026-03-04,23:14:01,Beeramguda,NaN,NaN,NaN,NaN,NaN


In [205]:
blinkit_s.loc[(blinkit_s["mrp"]!="Out of Stock")& (blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()),"Delivery_Charges(Handelling+Delivery)"]=27

In [206]:
blinkit_s[blinkit_s["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([27., 29., 25., 21.])

In [207]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:44:59,Beeramguda,0.0,Afternoon,NaN,Sunny,No
7,7,Sids Farm Cow Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:46:26,Beeramguda,0.0,Afternoon,NaN,Sunny,No
12,12,FreshtoHome Chicken - Skinless Curry Cut,Chicken,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:47:27,Beeramguda,0.0,Afternoon,NaN,Sunny,No
14,14,Super Cool Frozen Skinless Chicken Drumstickso...,Chicken,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:47:52,Beeramguda,0.0,Afternoon,NaN,Sunny,No
15,15,Organically Grown Onion (Ulligadda),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:04,Beeramguda,0.0,Afternoon,NaN,Sunny,No
17,17,Desi Tomato (Tamatar),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:31,Beeramguda,0.0,Afternoon,NaN,Sunny,No
18,18,Hybrid Tomato (Tamatar),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:48:44,Beeramguda,0.0,Afternoon,NaN,Sunny,No
20,20,Premier Mutton Curry Cut,Meat,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:08,Beeramguda,0.0,Afternoon,NaN,Sunny,No
21,21,Potato-(Bangala Dumpa),Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:21,Beeramguda,0.0,Afternoon,NaN,Sunny,No
22,22,Oraganically Grown Potato,Vegetable,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,12:49:33,Beeramguda,0.0,Afternoon,NaN,Sunny,No


In [208]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"].isna().sum()

Unnamed: 0                                0
name                                      0
Category                                  0
mrp                                       0
selling_price                             0
offer_percentage                          0
delivery_time                             0
quantity                                  0
scrape_date                               0
scrape_time                               0
location                                  0
Delivery_Charges(Handelling+Delivery)     3
Period                                    3
Surge                                    27
Climate                                   3
Surge_charges                             3
dtype: int64

In [209]:
blinkit_s.loc[(blinkit_s["mrp"]=="Out of Stock")&(blinkit_s["Delivery_Charges(Handelling+Delivery)"].isna()),"Delivery_Charges(Handelling+Delivery)"]=0

In [210]:
blinkit_s[blinkit_s["mrp"]=="Out of Stock"].isna().sum()

Unnamed: 0                                0
name                                      0
Category                                  0
mrp                                       0
selling_price                             0
offer_percentage                          0
delivery_time                             0
quantity                                  0
scrape_date                               0
scrape_time                               0
location                                  0
Delivery_Charges(Handelling+Delivery)     0
Period                                    3
Surge                                    27
Climate                                   3
Surge_charges                             3
dtype: int64

In [212]:
bigbasket_main=pd.concat([bigbasket_a,bigbasket_su,bigbasket_s],ignore_index=True)

In [213]:
bigbasket_main

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery+Late_Night_Charge),Delivery_Charges(Handelling+Delivery+Late_Night_Charges)
0,0,Heritage Fresh Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03-03-2026,23:34:32,KPHB colony,0.0,Night,NaN,Clear,No,11.0,NaN,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,150,125,17% OFF,18 MINS,240 g - Pouch,03-03-2026,23:34:43,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,20 MINS,500 ml - Pouch,03-03-2026,23:34:54,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,18 MINS,500 ml,03-03-2026,23:35:05,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
4,4,Arokya Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03-03-2026,23:35:17,KPHB colony,37.0,Night,NaN,Clear,No,11.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,35,fresho! Nagpur Orange,Fruit,129,79,39% OFF,8 MINS,1 kg - (Approx. 6 - 8 pcs),06-03-2026,09:09:26,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
956,36,fresho! Mini Orange Imported,Fruit,144,115.2,20% OFF,8 MINS,500 g,06-03-2026,09:09:36,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
957,37,fresho! Lemon,Vegetable,54,38.5,29% OFF,8 MINS,250 g,06-03-2026,09:09:47,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0
958,38,"fresho! Chilli - Green Long, Medium",Vegetable,17,11,35% OFF,8 MINS,100 g,06-03-2026,09:09:57,Beeramguda,21.0,Morning,NaN,Clear,No,NaN,NaN,21.0


In [214]:
bigbasket_main.duplicated().sum()

np.int64(0)

In [217]:
bigbasket_main[bigbasket_main["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([37., 26., 21., 32., 35.])

In [215]:
bigbasket_main["scrape_date"].unique()

array(['03-03-2026', '04-03-2026', '05-03-2026', '06-03-2026',
       '2026-03-06', '03/03/2026', '2026-03-04', '2026-03-05'],
      dtype=object)

In [216]:
bigbasket_main.to_csv("bigbasket_main.csv",index=False)

In [100]:
bigbasket_s

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery+Late_Night_Charges),Period,Surge,Climate,Surge_charges,Late_Night_Charges,Delivery_Charges(Handelling+Delivery),Delivery_Charges(Handelling+Delivery+Late_Night_Charge)
0,0,Heritage Fresh Paneer,Paneer,114,102,11% OFF,20 MINS,200 g - Pouch,03/03/2026,11:36:02 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
1,1,Heritage Nourish High Protein Paneer,Paneer,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:12 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
2,2,Heritage Daily Health Toned Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:21 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
3,3,Heritage Full Cream Milk,Milk,42,40,5% OFF,19 MINS,500 ml,03/03/2026,11:36:31 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
4,4,Arokya Full Cream Milk,Milk,Out of Stock,Out of Stock,Out of Stock,Out of Stock,Out of Stock,03/03/2026,11:36:41 PM,Madhapur,30.0,Night,NaN,Clear,No,9.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,35,fresho! Nagpur Orange,Fruit,129.0,79.0,39% OFF,14 MINS,1 kg - (Approx. 6 - 8 pcs),2026-03-06,14:59:35,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
316,36,fresho! Mini Orange Imported,Fruit,144.0,115.2,20% OFF,14 MINS,500 g,2026-03-06,14:59:46,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
317,37,fresho! Lemon,Vegetable,89.0,71.2,20% OFF,14 MINS,500 g,2026-03-06,15:00:01,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0
318,38,"fresho! Chilli - Green Long, Medium",Vegetable,17.0,11.0,35% OFF,14 MINS,100 g,2026-03-06,15:00:12,Gachibowli,NaN,Afternoon,NaN,Sunny,No,NaN,NaN,21.0


In [218]:
blinkit_main=pd.concat([blinkit_a,blinkit_su,blinkit_s],ignore_index=True)

In [219]:
blinkit_main

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
0,0,Heritage Fresh Paneer,Paneer,115.0,101,12% OFF,13 MINS,200 g,2026-03-03,12:56:15,KPHB colony,36.0,Afternoon,NaN,sunny,No
1,1,Heritage Nourish+ High Protein Paneer,Paneer,150.0,125,16% OFF,13 MINS,240 g,2026-03-03,12:56:29,KPHB colony,36.0,Afternoon,NaN,sunny,No
2,2,Heritage Daily Health Toned Milk,Milk,32,32,NaN,13 MINS,500 ml,2026-03-03,12:56:44,KPHB colony,36.0,Afternoon,NaN,sunny,No
3,3,Heritage Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:56:59,KPHB colony,36.0,Afternoon,NaN,sunny,No
4,4,Arokya Full Cream Milk,Milk,42,42,NaN,13 MINS,500 ml,2026-03-03,12:57:15,KPHB colony,36.0,Afternoon,NaN,sunny,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155,35,Nagpur - Orange,Fruit,67.0,59,11% OFF,8 MINS,500 g,2026-03-06,08:59:26,Beeramguda,27.0,Morning,NaN,Clear,No
1156,36,Mini Orange (Imported),Fruit,71.0,57,19% OFF,8 MINS,200 g,2026-03-06,08:59:39,Beeramguda,27.0,Morning,NaN,Clear,No
1157,37,Lemon (Nimakaya),Vegetable,45.0,38,15% OFF,8 MINS,200 g,2026-03-06,08:59:52,Beeramguda,27.0,Morning,NaN,Clear,No
1158,38,Green Chilli (Mirapakaya),Vegetable,13.0,11,15% OFF,8 MINS,100 g,2026-03-06,09:00:06,Beeramguda,27.0,Morning,NaN,Clear,No


In [220]:
blinkit_main.duplicated().sum()

np.int64(1)

In [221]:
blinkit_main[blinkit_main.duplicated()]

,Unnamed: 0,name,Category,mrp,selling_price,offer_percentage,delivery_time,quantity,scrape_date,scrape_time,location,Delivery_Charges(Handelling+Delivery),Period,Surge,Climate,Surge_charges
901,20,Premier Mutton Curry Cut,Meat,799,485,39% OFF,13 MINS,480 g,04-03-2026,08:06:35,Beeramguda,27.0,Morning,NaN,Clear,No


In [222]:
bigbasket_main[bigbasket_main["mrp"]!="Out of Stock"]["Delivery_Charges(Handelling+Delivery)"].unique()

array([37., 26., 21., 32., 35.])

In [121]:
blinkit_main.iloc[900]

Unnamed: 0                                                     20
name                                     Premier Mutton Curry Cut
Category                                                     Meat
mrp                                                           799
selling_price                                                 485
offer_percentage                                          39% OFF
delivery_time                                             13 MINS
quantity                                                    480 g
scrape_date                                            04-03-2026
scrape_time                                              08:06:35
location                                               Beeramguda
Delivery_Charges(Handelling+Delivery)                        27.0
Period                                                    Morning
Surge                                                         NaN
Climate                                                     Clear
Surge_char

In [122]:
blinkit_main.iloc[902]

Unnamed: 0                                                      22
name                                     Oraganically Grown Potato
Category                                                 Vegetable
mrp                                                             40
selling_price                                                   35
offer_percentage                                           12% OFF
delivery_time                                              17 MINS
quantity                                                    250 g 
scrape_date                                             04-03-2026
scrape_time                                               08:07:04
location                                                Beeramguda
Delivery_Charges(Handelling+Delivery)                         27.0
Period                                                     Morning
Surge                                                          NaN
Climate                                                      C

In [223]:
blinkit_main.to_csv("blinkit_main.csv",index=False)